schema {
  query: Query
}

type Query {
  hello(name: String!, input: InputObjectInput!): String!
}

input InputObjectInput @custom {
  name: String! @custom
}

"Defines when a policy shall be executed."
enum ApplyPolicy {
  "Before the resolver was executed."
  BEFORE_RESOLVER
  "After the resolver was executed."
  AFTER_RESOLVER
  "The policy is applied in the validation step before the execution."
  VALIDATION
}

directive @custom on
  | OBJECT
  | FIELD_DEFINITION
  | ARGUMENT_DEFINITION
  | INPUT_OBJECT
  | INPUT_FIELD_DEFINITION
