schema {
  query: Query
}

type Query {
  hello(name: String!): String!
  nestedInstance: NestedInstance!
  hello2(name: String! @validation): String!
}

type NestedInstance {
  helloExt(name: String!): String!
  hello1(name: String! @validation): String!
}

"Defines when a policy shall be executed."
enum ApplyPolicy {
  "Before the resolver was executed."
  BEFORE_RESOLVER
  "After the resolver was executed."
  AFTER_RESOLVER
  "The policy is applied in the validation step before the execution."
  VALIDATION
}

directive @validation on
  | FIELD_DEFINITION
  | ARGUMENT_DEFINITION
  | INPUT_FIELD_DEFINITION
